source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ProtobufClient' do

  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'SwiftProtobuf', :git => 'git@github.com:apple/swift-protobuf.git', :tag => '0.9.24'
  pod 'Protobuf', :path => '../protos'

end
